//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namordnik.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MaterialsProduct = new HashSet<MaterialsProduct>();
        }
    
        public string name_product { get; set; }
        public string articul { get; set; }
        public double min_cost { get; set; }
        public string images { get; set; }
        public string tip_product { get; set; }
        public int kol_for_proizv { get; set; }
        public int number_proizv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsProduct> MaterialsProduct { get; set; }
        public virtual product_sale product_sale { get; set; }
    }
}
